version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URI=mysql+pymysql://root:2004@mysql/cloudy_members
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=2004
      - MYSQL_DATABASE=cloudy_members
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: